-- CASE
SELECT TITLE, RELEASED_YEAR,
	CASE 
		WHEN RELEASED_YEAR >= 2000 THEN 'Modern Lit'
		ELSE '20th Century Lit'
	END AS GENRE
FROM BOOKS;

--
SELECT TITLE,PAGES,
	CASE
		WHEN STOCK_QUANTITY BETWEEN 0 AND 50 THEN '*'
        WHEN STOCK_QUANTITY BETWEEN 51 AND 100 THEN '**'
        ELSE '***'
    END AS stocks
FROM BOOKS;
