-- Comparing Dates
select * from people WHERE BIRTHDATE > '2020-01-01';
# OR
SELECT * FROM PEOPLE WHERE YEAR(BIRTHDATE) > 2020;
SELECT * FROM PEOPLE WHERE DAY(BIRTHDATE) > 0;
-- TIME
SELECT * FROM PEOPLE WHERE HOUR(BIRTHTIME) > 20;

# use of CAST
SELECT * FROM PEOPLE WHERE BIRTHTIME BETWEEN CAST('09:08:10' AS TIME) 
AND
CAST('23:23:23' AS TIME);