-- CURDATE, CURTIME, & NOW
/*
CURDATE()	Return the current date
CURRENT_DATE(), CURRENT_DATE	Synonyms for CURDATE()
CURRENT_TIME(), CURRENT_TIME	Synonyms for CURTIME()
CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP Synonyms for NOW()
*/
SELECT CURDATE();
-- OR 
SELECT CURRENT_DATE();
select curtime();
-- OR
SELECT CURRENT_TIME();
select now();	
-- OR 
SELECT CURRENT_TIMESTAMP();

INSERT INTO PEOPLE (name, BIRTHDATE, BIRTHTIME, BIRTHDT)
VALUES
('Eslon',CURDATE(),CURTIME(), NOW());