SELECT 
	MAX(CASE WHEN OCCUPATION = 'Doctor' THEN Name END) AS DOCTOR,
    MAX(CASE WHEN OCCUPATION = 'Professor' THEN NamE END) AS PROFESSOR,
    MAX(CASE WHEN OCCUPATION = 'Singer' THEN NamE END) AS SINGER,
    MAX(CASE WHEN OCCUPATION = 'Actor' THEN NamE END) AS ACTOR
FROM (SELECT OCCUPATION , Name, ROW_NUMBER() OVER (PARTITION BY OCCUPATION ORDER BY NAME) as rn FROM OCCUPATIONS) as sorted_columns
GROUP BY rn 