-- Date Math
-- DATEDIFF()
SELECT BIRTHDATE, DATEDIFF(CURDATE(), BIRTHDATE) FROM PEOPLE;
-- date_add()
-- DATE_ADD(date, INTERVAL expr unit)
/*
	where expr is number
		  unit is hour, year like that
*/
SELECT BIRTHDATE, DATE_ADD(BIRTHDATE,INTERVAL 2 DAY) FROM PEOPLE;
SELECT BIRTHDATE, DATE_ADD(BIRTHDATE,INTERVAL 2 WEEK) FROM PEOPLE;
SELECT BIRTHDATE, DATE_ADD(BIRTHDATE,INTERVAL 2 MONTH) FROM PEOPLE;
SELECT BIRTHDATE, DATE_ADD(BIRTHDATE,INTERVAL 2 YEAR) FROM PEOPLE;
-- it also works with TIME
SELECT BIRTHTIME, DATE_ADD(BIRTHTIME,INTERVAL 1 SECOND) FROM PEOPLE;
SELECT BIRTHTIME, DATE_ADD(BIRTHTIME,INTERVAL 1 MINUTE) FROM PEOPLE;
SELECT BIRTHTIME, DATE_ADD(BIRTHTIME,INTERVAL 1 HOUR) FROM PEOPLE;
-- date_sub()
-- DATE_SUB(date, INTERVAL expr unit)
/*
	where expr is number
		  unit is hour, year like that
*/
SELECT BIRTHDATE, DATE_SUB(BIRTHDATE,INTERVAL 2 DAY) FROM PEOPLE;
SELECT BIRTHDATE, DATE_SUB(BIRTHDATE,INTERVAL 2 WEEK) FROM PEOPLE;
SELECT BIRTHDATE, DATE_SUB(BIRTHDATE,INTERVAL 2 MONTH) FROM PEOPLE;
SELECT BIRTHDATE, DATE_SUB(BIRTHDATE,INTERVAL 2 YEAR) FROM PEOPLE;
-- it also works with TIME
SELECT BIRTHTIME, DATE_SUB(BIRTHTIME,INTERVAL 1 SECOND) FROM PEOPLE;
SELECT BIRTHTIME, DATE_SUB(BIRTHTIME,INTERVAL 1 MINUTE) FROM PEOPLE;
SELECT BIRTHTIME, DATE_SUB(BIRTHTIME,INTERVAL 1 HOUR) FROM PEOPLE;
/* 
OR WE CAN USE DIRECTLY
TIMEDIFF(),
ADD_TIME(),
SUBTIME()
*/