-- AT - Modifying Columns

# ALTER TABLE {TABLE_NAME}
# MODIFY {COL_NAME} {DATA_TYPE_TO_CHANGE};
ALTER TABLE CONTACTS
MODIFY number1 VARCHAR(30);

# ALTER TABLE {TABLE_NAME}
# CHANGE {OLD_COL_NAME} {NEW_COL_NAME} {DATA_TYPE};
ALTER TABLE CONTACTS
CHANGE PHONE number1 VARCHAR(20);

SELECT * FROM CONTACTS;
DESC CONTACTS;