-- AT - Add or Delete Contraints
SHOW TABLES;
SELECT * FROM CONTACTS;
# ALTER TABLE {TABLE_NAME} ADD CONSTRAINT {CONSTRAINT_NAME}
# CHECK {CONDITION}
ALTER TABLE CONTACTS ADD CONSTRAINT phone_no
CHECK (length(number1) >= 10);

INSERT INTO CONTACTS VALUES('asda','90876754');
-- ERROR

# IF WE HAVE TO REMOVE THE CONSTRAINTS
# alter table {table_name}
# DROP CONSTRAINT {CONSTRAINT_NAME}

ALTER TABLE CONTACTS
DROP CONSTRAINT phone_no;

INSERT INTO CONTACTS VALUES('asda','90876754');
-- NO ERROR