-- CHECK Constraint

CREATE TABLE USERS(
	USERNAME VARCHAR(25),
    AGE INT CHECK(AGE >= 18)
);

INSERT INTO USERS VALUES('john',21);

INSERT INTO USERS VALUES('monk', 34);

INSERT INTO USERS VALUES('jaahn', 4); -- ERROR

SELECT * FROM USERS; 

# check for palindrom

CREATE TABLE PALINDROME(
	word VARCHAR(100) CHECK(REVERSE(WORD) = WORD)
);


INSERT INTO PALINDROME (word) VALUES ('racecar');


INSERT INTO PALINDROME (word) VALUES ('john'); -- ERROR


SELECT * FROM PALINDROME;